dataSource:
  dialect: MySQL
  driver: org.postgresql.Driver
  url: "jdbc:postgresql://localhost:5432/demo?useUnicode=true&amp;characterEncoding=utf8"
  username: postgres
  password: postgres

tables:
  - domainObjectName: User
    tableComment: "用户"
    tableName: xmo_user
    modulePackage: com.xmomen.module.test
    restMapping: /user