dataSource:
  dialect: MySQL
  driver: org.postgresql.Driver
  url: "jdbc:postgresql://localhost:5432/demo?useUnicode=true&amp;characterEncoding=utf8"
  username: postgres
  password: postgres

metadata:
  templateDirectory: "/Users/jeng/tanxinzheng-repo/xmomen-repo/framework/xmomen-generator/xmomen-generator-core/src/main/resources/templates/"
  outputDirectory: "/Users/jeng/tanxinzheng-repo/xmomen-repo/framework/xmomen-generator/xmomen-generator-core/src/test/java"
  ignoreKeywordValidate: true

tables:
  - domainObjectName: User
    tableComment: "用户"
    tableName: xmo_user
    modulePackage: com.xmomen.module.test
    restMapping: /user